config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  } 
  # User posts routes
  get '/forum' => 'posts#index', as: 'forum'
  get '/users/:user_id/posts/new' => 'posts#new', as: 'new_user_post'
  post '/users/:user_id/posts' => 'posts#create', as: 'user_posts'
  get '/users/:user_id/posts/:id' => 'posts#show', as: 'user_post'
  get '/users/:user_id/posts/:id/edit' => 'posts#edit', as: 'edit_user_post'
  patch '/users/:user_id/posts/:id' => 'posts#update'
  delete '/users/:user_id/posts/:id' => 'posts#destroy'
  
  # Post comments routes
  post '/posts/:post_id/comments' => 'comments#create', as: 'post_comments'
  patch '/posts/:post_id/comments/:id' => 'comments#update', as: 'update_post_comment'
  delete '/posts/:post_id/comments/:id' => 'comments#destroy', as: 'delete_post_comment'

  get 'calculator/index'

  # User assignments routes
  get '/assignments' => 'assignments#index', as: 'assignments'
  get '/users/:user_id/assignments/new' => 'assignments#new', as: 'new_user_assignment'
  post '/users/:user_id/assignments' => 'assignments#create', as: 'user_assignments'
  get '/users/:user_id/assignments/:id' => 'assignments#show', as: 'user_assignment'
  get '/users/:user_id/assignments/:id/edit' => 'assignments#edit', as: 'edit_user_assignment'
  patch '/users/:user_id/assignments/:id' => 'assignments#update'
  delete '/users/:user_id/assignments/:id' => 'assignments#destroy'

  # Assignment editor routes
  patch '/assignments/:assignment_id/editors' => 'editors#update', as: 'assignment_editor'
  delete '/assignments/:assignment_id/editors/:id' => 'editors#destroy'

  resources :admin
  resources :workspace
  
  
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  validates :title,  presence: true
  validates :todo,   presence: true
  validates :due_date, presence: true

  belongs_to :user, optional: true
  has_many :editors
  has_one_attached :image
  has_one_attached :file

  FILE_VALIDATIONS = {
    content_type: ["application/pdf"],
    max_size: 5.megabytes,
    min_size: 1.kilobyte
  }

  def is_pdf?
    self.content_type == "application/pdf"
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  def index
    @assignment = Assignment.all
    @user = User.all
  end

  def show
    @user = User.find(params[:user_id])
    @assignment = @user.assignments.find(params[:id])
    @editor = @assignment.editors.new
    
    respond_to do |format|
      format.html
      format.pdf do
        pdf = Prawn::Document.new
        pdf.text params[:contents]
        send_data(pdf.render, filename: "#{ @assignment.title }-workspace-session.pdf", type: "application/pdf")
      end
    end
  end

  def new
    @assignment = Assignment.new
  end

  def create
    if params[:assignment][:image].nil? && params[:assignment][:file].nil?
      @assignment = current_user.assignments.create!(params.require(:assignment).permit(:title, :due_date, :todo))
    elsif params[:assignment][:image].nil?
      @assignment = current_user.assignments.create!(params.require(:assignment).permit(:title, :due_date, :todo))
      @assignment.file.attach(params[:assignment][:file])
    elsif params[:assignment][:file].nil?
      @assignment = current_user.assignments.create!(params.require(:assignment).permit(:title, :due_date, :todo))
      @assignment.image.attach(params[:assignment][:image])
    else
      @assignment = current_user.assignments.create!(params.require(:assignment).permit(:title, :due_date, :todo))
      @assignment.image.attach(params[:assignment][:image])
      @assignment.file.attach(params[:assignment][:file])
    end
    redirect_to assignments_path
  end

  def edit
    @assignment = Assignment.find(params[:id])
  end

  def update
    @assignment = Assignment.find(params[:id])
    @assignment.update(params.require(:assignment).permit(:title, :due_date, :todo))
    redirect_to user_assignment_path(@assignment.user, @assignment)
  end

  def destroy
    @assignment = Assignment.find(params[:id])
    @assignment.destroy
    redirect_to assignments_path
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/edit.html.erb
<% content_for :title, "Edit Assignment" %>

<div class="text-center">
    <h1 class="card-title" style="margin: 2rem;">Edit Assignment</h1>
</div>

<%= form_with(model: @assignment, url: assignments_path) do |f| %>
    <div class="form-group new-comment-form" style="width: 65%; margin-left: auto; margin-right: auto">
        <div class="form-group">
            <%= f.label :title %> 
            <%= f.text_field :title, class: "form-control" %> 
        </div>
        <div class="form-group">
            <%= f.label :due_date %> 
            <%= f.date_field :due_date, class: "form-control" %>
        </div>
        <%= f.label :upload_files_below %>
        <div class="input-group mb-3">
            <div class="custom-file">
                <%= f.file_field :image, class: "form-control-file upload-btn" %>
                <% if @assignment.image.attached? %>
                    <label for="assignment_choose_image" class="custom-file-label upload-label"><%= @assignment.image.filename.to_s %></label>
                <% else %>
                    <%= f.label :choose_image, class: "custom-file-label upload-label" %>
                <% end %>
            </div> 
        </div>
        <div class="input-group mb-3">
            <div class="custom-file">
                <%= f.file_field :file, class: "form-control-file upload-btn" %>
                <% if @assignment.file.attached? %>
                    <label for="assignment_choose_file" class="custom-file-label upload-label"><%= @assignment.file.filename.to_s %></label>
                <% else %>
                    <%= f.label :choose_document, class: "custom-file-label upload-label" %>
                <% end %>
            </div> 
        </div>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.submit "Update Assignment", class: "btn btn-primary comment-submit-btn" %>
    </div>
<% end %>

<div class="text-center">
    <%= link_to :back do %>
        <button type="button" class="btn btn-success text-white mt-4 mb-3 back-btn">
            Back
        </button>
    <% end %>
</div>

app/views/assignments/index.html.erb
<% content_for :title, "Assignments" %>
<div class="assignments" style="height: 35rem; width: 100%">

  <h1>Assignment</h1>

  <%= link_to new_user_assignment_path(current_user) do %>
    <button type="button" class="btn btn-success">New Assignment</button>
    <% end %>
    <br><br>
    <% @assignment.each do |assignment| %>
    <%= link_to assignment.title, user_assignment_path(current_user, assignment) %>
    (<%= assignment.due_date%>)
    <br><br>
  <% end %>
</div>

app/views/assignments/new.html.erb
<% content_for :title, "Create New Assignment" %>

<%= flash[:file_error] %>

<div class="row">
  <div class="card">
    <div class="card-body">
      <h2 class="card-title">Create Assignment</h2>
        <%= form_with(model: @assignment, html: {multipart:true}, url: user_assignments_path(current_user), method: :post) do |form| %>
        <label> Title</label><br>
        <%= form.text_field :title, :size=>"58", placeholder: "Title", :maxlength=>"150" %> <br>
        <label>Due date</label><br>
        <%= form.date_field :due_date %> <br>
        <label> Description</label><br>
        <%= form.text_area :todo, cols: "60", rows: "10"%> <br>

        <div class="image-upload">
          <label for="img-input">
          <span class="far fa-images">
          </span> Upload Image</label>
          <%= form.file_field :image, id: "img-input" %><br>
        </div>

        <div class="image-upload">
          <label for="file-input">
          <span class="far fa-file-pdf">
          </span>  Upload PDF</label>
        <%= form.file_field :file, id: "file-input" %><br><br>
        </div>
        
        <%= form.submit "Add Assignment", {class: "btn btn-primary"} %><br><br>

        <%= link_to "Back", :back, {class: "back-link"} %>
        <% end %>
    </div>
  </div>
</div>

app/views/assignments/show.html.erb
<% content_for :title, "Assignment" %>


<div class="text-center mx-auto">
    <div class="header-btn-container" style="margin-top: 5rem;">
        <%= link_to root_path do %>
            <button type="button" class="btn btn-success text-white mt-3 mb-3 back-btn">
                Back
            </button>
        <% end %>

        <%= link_to edit_user_assignment_path do %>
        <button type="button" class="btn btn-primary mt-3 mb-3">
        Edit
        </button>
        <% end %>

        <%= link_to user_assignment_path(current_user, @assignment), method: :delete  do %>
        <button type="button" class="btn btn-danger mt-3 mb-3 delete-btn">
        Delete
        </button>
        <% end %>
    </div>

    <div class="container-fluid center">
    <table class="table table-bordered text-center assignment-table" style="color: white">
        <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Due Date</th>
            <th scope="col">Image</th>
            <th scope="col">File</th>
        </tr>
        </thead>

        <tbody>
            <tr>
                <td>
                    <strong><%= @assignment.title %></strong>
                <br>
                </td>

                <td>
                <%= @assignment.todo %>
                <br><br>
                </td>

                <td>
                    <%= @assignment.due_date %>
                    <br>
                </td>

                <td>
                    <% if @assignment.image.attached? %>
                        <%= image_tag(@assignment.image, width: '200') %>
                    <% end %> <br>
                </td>

                <td>
                    <% if @assignment.file.attached? %>
                        <%= link_to "Download File", @assignment.file, download: '' %>
                    <% end %>
                </td>
            </tr>
        </tbody>
    </table>
    </div>    

    <div class="row editor-form">
        <% if @assignment.file.attached? %>
            <div class="col-6 row assgn-col pdf-col">
                <h3>PDF Viewer</h3>
                <embed src="<%= rails_blob_path(@assignment.file) %>" type="application/pdf" width="600rem" height="600rem">
            </div>

            <div class="col-6 assgn-col editor-col">
                <h3>Text Editor</h3>
                <div id="editor" style="height: 85vh">
                    <% unless @assignment.editors.length == 0 %>
                        <% @assignment.editors.each do |editor| %>
                            <%== editor.session %>
                        <% end %>
                    <% end %>
                </div>
                <div>
                    <%= form_with(model: @editor, url: assignment_editor_path(@assignment), method: :patch, class: "session-form") do |f| %>
                        <%= f.hidden_field :session, class: "session-input" %>
                        <%= f.submit "Save", class: "btn btn-success m-2 text-white save-session-btn" %>
                    <% end %>
                    <%= link_to user_assignment_path(@assignment.user, @assignment, format: 'pdf', contents: "hello world"), class: "editor-contents" do %>
                        <button class="btn btn-success mt-2 mb-2 text-white download-as-pdf-btn" role="button">
                            Download
                        </button>
                    <% end %>
                </div>
            </div>
        <% else %>

            <div class="editor-container">
                <div class="editor-wrapper">
                    <h3>Text Editor</h3>
                    <!-- Create the editor container -->
                    
                    <div id="editor">
                        <% unless @assignment.editors.length == 0 %>
                            <% @assignment.editors.each do |editor| %>
                                <%== editor.session %>
                            <% end %>
                        <% end %>
                    </div>
                    <div class="text-center" style="display: inline-block">
                        <%= form_with(model: @editor, url: assignment_editor_path(@assignment), method: :patch, class: "session-form") do |f| %>
                            <%= f.hidden_field :session, class: "session-input" %>
                            <%= f.submit "Save", class: "btn btn-success m-2 text-white save-session-btn" %>
                        <% end %>
                        <%= link_to user_assignment_path(@assignment.user, @assignment, format: 'pdf'), class: "editor-contents" do %>
                            <button class="btn btn-success mt-2 mb-2 text-white download-as-pdf-btn" role="button">
                                Download
                            </button>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>

</div>