config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  } 
  # User posts routes
  get '/forum' => 'posts#index', as: 'forum'
  get '/users/:user_id/posts/new' => 'posts#new', as: 'new_user_post'
  post '/users/:user_id/posts' => 'posts#create', as: 'user_posts'
  get '/users/:user_id/posts/:id' => 'posts#show', as: 'user_post'
  get '/users/:user_id/posts/:id/edit' => 'posts#edit', as: 'edit_user_post'
  patch '/users/:user_id/posts/:id' => 'posts#update'
  delete '/users/:user_id/posts/:id' => 'posts#destroy'
  
  # Post comments routes
  post '/posts/:post_id/comments' => 'comments#create', as: 'post_comments'
  patch '/posts/:post_id/comments/:id' => 'comments#update', as: 'update_post_comment'
  delete '/posts/:post_id/comments/:id' => 'comments#destroy', as: 'delete_post_comment'

  get 'calculator/index'

  # User assignments routes
  get '/assignments' => 'assignments#index', as: 'assignments'
  get '/users/:user_id/assignments/new' => 'assignments#new', as: 'new_user_assignment'
  post '/users/:user_id/assignments' => 'assignments#create', as: 'user_assignments'
  get '/users/:user_id/assignments/:id' => 'assignments#show', as: 'user_assignment'
  get '/users/:user_id/assignments/:id/edit' => 'assignments#edit', as: 'edit_user_assignment'
  patch '/users/:user_id/assignments/:id' => 'assignments#update'
  delete '/users/:user_id/assignments/:id' => 'assignments#destroy'

  # Assignment editor routes
  patch '/assignments/:assignment_id/editors' => 'editors#update', as: 'assignment_editor'
  delete '/assignments/:assignment_id/editors/:id' => 'editors#destroy'

  resources :admin
  resources :workspace
  
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  validates :first_name,  presence: true
  validates :last_name,   presence: true
  validates :email,   presence: true
  validates :password, presence: true

  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  validates :title,  presence: true
  validates :todo,   presence: true
  validates :due_date, presence: true

  belongs_to :user, optional: true
  has_many :editors
  has_one_attached :image
  has_one_attached :file

  FILE_VALIDATIONS = {
    content_type: ["application/pdf"],
    max_size: 5.megabytes,
    min_size: 1.kilobyte
  }

  def is_pdf?
    self.content_type == "application/pdf"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
    has_one_attached :image
end

app/models/editor.rb
class Editor < ApplicationRecord
    belongs_to :assignment
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments
    has_one_attached :image
end

app/models/student.rb
class Student < ApplicationRecord
  validates :first_name,  presence: true
  validates :last_name,   presence: true
  validates :email,   presence: true
  validates :password, presence: true

  has_many :assignments
  has_secure_password

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :assignments, dependent: :destroy
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    
  # def index
  #   @student = Student.all
    
  # end

  # def show
    
  #   @student = Student.find(params[:id])
  # end

  # def new
  #   @student = Student.new
  # end

  # def create
  #  @student = Student.new(student_params)
  #  if @student.valid?
  #    @student.save
  #    redirect_to home_index_path
  #   end
  # end

  # def edit
  #   @student = Student.find(params[:id])
  # end

  # def update
  #   @student = Student.find(params[:id])
  #   @student.update(student_params)
  #   redirect_to home_index_path
  # end

  # def destroy
  # Student.destroy(params[:id])
  # redirect_to home_index_path
  # end

  # def student_params
  #   params.require(:student).permit(:first_name, :last_name)
  # end
end

app/controllers/editors_controller.rb
class EditorsController < ApplicationController
    def update
        @assignment = Assignment.find(params[:assignment_id])
        unless @assignment.editors.length == 0
            @assignment.editors.destroy_all
        end
        @assignment.editors.create(
            assignment_id: params[:assignment_id],
            session: params[:editor][:session]
            )
        puts params[:session]
        redirect_to user_assignment_path(@assignment.user, @assignment)
    end

    def destroy
        @assignment = Assignment.find(params[:assignment_id])
        @editor = @assignment.editor
        @editor.destroy
        redirect_to user_assignment_path(@assignment.user, @assignment)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
    @assignments = current_user.assignments.all
    @posts = current_user.posts.with_attached_image
  end

  def home
    if !logged_in?
      redirect_to login_path
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all.order(:id)
        @user = User.all
    end

    def new
        @post = Post.new
    end

    def create
        if params[:post][:image].nil?
            @post = current_user.posts.create!(params.require(:post).permit(:title, :content))
        else
            @post = current_user.posts.create!(params.require(:post).permit(:title, :content))
            @post.image.attach(params[:post][:image])
        end
        redirect_to root_path
    end
    
    def show
        @post = Post.find(params[:id])
        @comment = @post.comments
    end

    def edit
        @user = User.find(params[:user_id])
        @post = @user.posts.find(params[:id])
    end

    def update
        @user = User.find(params[:user_id])
        @post = @user.posts.find(params[:id])
        if params[:post][:image].nil?
            @post.update(params.require(:post).permit(:title, :content))
        else
            @post.image.attach(params[:post][:image])
            @post.update(params.require(:post).permit(:title, :content))
        end
        redirect_to root_path
    end

    def destroy
        @user = User.find(params[:user_id])
        @post = @user.posts.find(params[:id])
        @post.destroy
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/calculator_helper.rb
module CalculatorHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/editors_helper.rb
module EditorsHelper
end

app/helpers/forum_helper.rb
module ForumHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/workspace_helper.rb
module WorkspaceHelper
end

app/views/home/index.html.erb
<% content_for :title, "Dashboard" %>

<div class="dashboard">
    <div class="row">
        <h1 style="color: white; margin-top: 4rem;"><br>Dashboard</h1>
    </div>

    <div class="row">
        <div class="col-5">      
            <h3 class="text-center" style="color: white;">Assignments
            <br><br>

            <%= link_to new_user_assignment_path(current_user) do %>
            <button type="button" class="btn btn-success">New Assignment </button>
            <% end %>
            <button type="button" data-toggle="collapse" data-target="#multiCollapseExample1" aria-expanded="false" aria-controls="multiCollapseExample1" class="btn btn-success">Quick View</button>
            </h3>
        </div>

        <div class="col-5">
            <h3 class="text-center" style="color: white;">Posts 
            <br> <br>

            <%= link_to new_user_post_path(current_user) do %>
            <button type="button" class="btn btn-success">New Post </button>
            <% end %>
            <button type="button" data-toggle="collapse" data-target="#multiCollapseExample2" aria-expanded="false" aria-controls="multiCollapseExample2" class="btn btn-success">Quick View</button>
            </h3>
        </div>
    </div>

    <div class="row">
        <div class="col-5 assignments collapse multi-collapse" id="multiCollapseExample1">    
            <table class="table table-hover text-center">
                <thead>
                <tr>
                    <th scope="col">Due date</th>
                    <th scope="col">Assignment</th>
                </tr>
                </thead>

                <tbody>
                <% @assignments.each do |assignment| %>
                    <tr>
                    <td>
                    <%= assignment.due_date%>
                    </td>
                    <td>
                    <%= link_to assignment.title, user_assignment_path(current_user, assignment) %>
                    </td>
                    </tr> 
                    <% end %>
                </tbody>
            </table> 
        </div>

 
 
 <div class="col-5 posts collapse multi-collapse" id="multiCollapseExample2">
            
    <table class="table table-hover text-center">
            <thead>
                <tr>
                     <th scope="col">Post</th>
                    <th scope="col">Updated</th>
                </tr>
             </thead>

         <tbody>
                <% @posts.each do |post| %>
            <tr>
             <td>
                <%= link_to post.title, user_post_path(current_user, post) %>
            </td>
            <td>
                <%= post.updated_at.to_formatted_s(:long).to_s[0..17] %>
            </td>

            </tr>
            <% end %>
        </tbody>
    </table>

</div>
</div>

app/views/posts/edit.html.erb
<% content_for :title, "Edit Post" %>
<div class="text-center">
    <h1 class="card-title" style="margin: 2rem;">Edit Post</h1>
</div>
    <%= form_with model: @post, url: user_post_path(@user, @post), method: :patch do |f| %>
        <div class="form-group new-comment-form" style="width: 65%; margin-left: auto; margin-right: auto">
            <div class="form-group">
                <%= f.label :title %> 
                <%= f.text_field :title, class: "form-control" %> 
            </div>
            <div class="form-group">
                <%= f.label :content %> 
                <%= f.text_area :content, class: "form-control", rows: "3" %>
                <small id="emailHelp" class="form-text text-muted">Say Something Nice 😉</small>
            </div>
            <div class="input-group mb-3">
                <div class="custom-file">
                <%= f.file_field :image, class: "form-control-file upload-btn" %>
                <% if @post.image.attached? %>
                    <label for="post_choose_image" class="custom-file-label upload-label"><%= @post.image.filename.to_s %></label>
                <% else %>
                    <%= f.label :choose_image, class: "custom-file-label upload-label" %> 
                <% end %>
                </div> 
            </div>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.submit "Update Post", class: "btn btn-primary comment-submit-btn" %>
        </div>
    <% end %>

<div class="text-center">
    <%= link_to :back do %>
        <button type="button" class="btn btn-success text-white mt-4 mb-3 back-btn">
            Back
        </button>
    <% end %>
</div>

app/views/posts/index.html.erb
<% content_for :title, "Public Forum" %>

<div>
    <div class="text-center">
        <h1 class="mt-4" style="color: white;" >Public Forum</h1>
        <%= link_to new_user_post_path(current_user) do %>
        <button type="button" class="btn btn-success mt-3">New Post</button>
        <% end %>
    </div>
<div style="display: flex">
    <div class="card col-11 forum-card" style="border: 1px solid black">
        <div class="card-header text-white bg-success forum-header">
            <span class="forum-heading-title-1">Post</span>
            <span class="forum-heading-title-2 text-center">Members</span>
            <span class="forum-heading-title-3 text-center">Comments</span>
            <span class="forum-heading-title-4 text-center">Posted By</span>
        </div>

        <% count = 0 %>
        <% @posts.each do |post| %>
        <div class="card-body forum-contents">
            <div class="forum-title-box">
                <h5 class="card-title forum-title-text forum-post-title"><%= link_to post.title, user_post_path(post.user, post) %></h5>
                <p class="card-text post-text"><%= post.content %></p>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalScrollable-<%= count %>">
                    View Highlights
                </button>
                <div class="modal fade" id="exampleModalScrollable-<%= count %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
                        <div class="highlight-box modal-dialog modal-dialog-scrollable modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalScrollableTitle"><%= post.title %></h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body highlight-text-box">   
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
            <div class="forum-members-box text-center">
                0
            </div>
            <div class="forum-comments-box text-center">
                <%= post.comments.count %>
            </div>
            <div class="forum-posted-box text-center">
                <small class="ml-2"><%= post.user.email %></small>
            </div>
        </div>
            <br>
            <% count += 1 %>  
        <% end %>
    </div>
</div>
</div>

app/views/posts/new.html.erb
<% content_for :title, "New Post" %>

<div class="row">
  <div class="card">
    <div class="card-body">
      <h2 class="card-title">Create Post</h2>
        <%= form_with(model: @post, local: true, url: user_posts_path(current_user), method: :post) do |f| %>
        <%= f.label :title %> <br>
        <%= f.text_field :title, :size=>"58", placeholder: "Title", :maxlength=>"150" %> <br><br>
        <%= f.label :content %> <br>
        <%= f.text_area :content, cols: "60", rows: "10" %> <br>
        <div class="image-upload">
          <label for="img_input">
          <span class="far fa-images">
          </span> Upload Image</label>
          <%= f.file_field :image, id: "img_input" %><br>
        </div><br>
        <%= f.submit "Create Post", {class: "btn btn-primary"} %>
        <% end %><br>

        <%= link_to "Back", :back, {class: "back-link"} %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% content_for :title, "Post" %>

<div class="post-header-btn-container text-center" style="margin-top: 5rem;">
    <%= link_to forum_path do %>
        <button type="button" class="btn btn-success text-white mt-4 mb-3 back-btn">
            Back
        </button>
    <% end %>

    <% if current_user %>
        <%= link_to edit_user_post_path(@post.user, @post) do %>
            <button type="button" class="btn btn-primary mt-4 mb-3">
                Edit
            </button>
        <% end %>
    <% end %>

    <% if current_user %>
        <%= link_to user_post_path(@post.user, @post), method: :delete  do %>
            <button type="button" class="btn btn-danger mt-4 mb-3 delete-btn">
                Delete
            </button>
        <% end %>
    <% end %>
</div>

<div class="post-container">
    <div class="card mb-3 post-card">
        <div class="row no-gutters">
            <% if @post.image.attached? %>
                <div class="col-md-4">
                    <%= image_tag(@post.image, class: "card-img post-img") %> <br>
                </div>
                <div class="col-md-8">
            <% else %>
                <div class="col-md-12">
            <% end %>
                <div class="card-body post-body">
                    <h5 class="card-title forum-title-text"><%= @post.title %></h5>
                    <hr>
                    <p class="card-text post-text"><%= @post.content %></p>
                    <div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
                            <div class="highlight-box modal-dialog modal-dialog-scrollable modal-dialog-centered" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalScrollableTitle"><%= @post.title %></h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body highlight-text-box">
                                        
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <div class="small-post-text">
                        <hr>
                        <div class="text-post-btn">
                            <p class="card-text"><small class="text-muted">Posted By: <%= @post.user.email %></small></p>
                            <button type="button" class="btn btn-primary post-btn" data-toggle="modal" data-target="#exampleModalScrollable">
                            View Highlights
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="card-header bg-dark text-center" style="width: 95%; margin: 1rem 0; margin-left: auto; margin-right: auto;">
    <h5 class="text-white card-title mt-2">
        Reply Below
    </h5>
</div>

<h4 class="comment-title">Comment Section - <%= @post.comments.count %></h4>
    <% @post.comments.each do |comment| %>
        <div class="comment">
            <div class="post-container">
                <div class="card mb-3 post-card comment-card">
                    <div class="row no-gutters">
                        <% if comment.image.attached? %>
                        <div class="col-md-4">
                            <%= image_tag(comment.image, class: "card-img post-img") %> <br>
                        </div>
                        <div class="col-md-8">
                        <% else %>
                        <div class="col-md-12">
                        <% end %>
                        <div class="card-body post-body">
                            <h5 class="card-title forum-title-text"><%= comment.title %></h5>
                            <hr>
                            <p class="card-text post-text"><%= comment.content %></p>
                            <div class="small-post-text">
                                <hr>
                                <div class="text-comment-btn">
                                    <p class="card-text post-user-email"><small class="text-muted">Posted By: <%= @post.user.email %></small></p>
                                    <div class="edit-btn-container">
                                        <% if current_user %>
                                            <button class="edit-comment-btn btn btn-primary">
                                                Edit
                                            </button>
                                        <% end %>
                                    </div>
                                    <% if current_user %>
                                        <%= link_to delete_post_comment_path(@post, comment), method: :delete, class: "delete-btn-link" do %>
                                            <button class="btn btn-danger">
                                                Delete
                                            </button>
                                        <% end %>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        <%= form_with model: comment, url: update_post_comment_path(@post, comment), method: :patch, class: "edit-comment-form" do |f| %>
            <div class="form-group new-comment-form">
                <div class="form-group">
                    <%= f.label :title %> 
                    <%= f.text_field :title, class: "form-control" %> 
                </div>
                <div class="form-group">
                    <%= f.label :content %> 
                    <%= f.text_area :content, class: "form-control", rows: "3" %>
                    <small id="emailHelp" class="form-text text-muted">Say Something Nice 😉</small>
                </div>
                <div class="input-group mb-3">
                    <div class="custom-file">
                        <%= f.file_field :image, class: "form-control-file upload-btn" %>
                        <% if comment.image.attached? %>
                            <label for="comment_choose_image" class="custom-file-label upload-label">
                                <%= comment.image.filename.to_s %>
                            </label>
                        <% else %>
                            <%= f.label :choose_image, class: "custom-file-label upload-label" %>
                        <% end %> 
                    </div> 
                </div>
                <%= f.hidden_field :user_id, :value => current_user.id %>
                <%= f.submit "Update Comment", class: "btn btn-primary comment-submit-btn" %>
                <button class="btn btn-danger cancel-edit-btn">
                    Cancel
                </button>
            </div>
        <% end %>
    <% end %>
<%= render "comments/form" %>