config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  } 
  # User posts routes
  get '/forum' => 'posts#index', as: 'forum'
  get '/users/:user_id/posts/new' => 'posts#new', as: 'new_user_post'
  post '/users/:user_id/posts' => 'posts#create', as: 'user_posts'
  get '/users/:user_id/posts/:id' => 'posts#show', as: 'user_post'
  get '/users/:user_id/posts/:id/edit' => 'posts#edit', as: 'edit_user_post'
  patch '/users/:user_id/posts/:id' => 'posts#update'
  delete '/users/:user_id/posts/:id' => 'posts#destroy'
  
  # Post comments routes
  post '/posts/:post_id/comments' => 'comments#create', as: 'post_comments'
  patch '/posts/:post_id/comments/:id' => 'comments#update', as: 'update_post_comment'
  delete '/posts/:post_id/comments/:id' => 'comments#destroy', as: 'delete_post_comment'

  get 'calculator/index'

  # User assignments routes
  get '/assignments' => 'assignments#index', as: 'assignments'
  get '/users/:user_id/assignments/new' => 'assignments#new', as: 'new_user_assignment'
  post '/users/:user_id/assignments' => 'assignments#create', as: 'user_assignments'
  get '/users/:user_id/assignments/:id' => 'assignments#show', as: 'user_assignment'
  get '/users/:user_id/assignments/:id/edit' => 'assignments#edit', as: 'edit_user_assignment'
  patch '/users/:user_id/assignments/:id' => 'assignments#update'
  delete '/users/:user_id/assignments/:id' => 'assignments#destroy'

  # Assignment editor routes
  patch '/assignments/:assignment_id/editors' => 'editors#update', as: 'assignment_editor'
  delete '/assignments/:assignment_id/editors/:id' => 'editors#destroy'

  resources :admin
  resources :workspace
  
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  validates :first_name,  presence: true
  validates :last_name,   presence: true
  validates :email,   presence: true
  validates :password, presence: true

  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  validates :title,  presence: true
  validates :todo,   presence: true
  validates :due_date, presence: true

  belongs_to :user, optional: true
  has_many :editors
  has_one_attached :image
  has_one_attached :file

  FILE_VALIDATIONS = {
    content_type: ["application/pdf"],
    max_size: 5.megabytes,
    min_size: 1.kilobyte
  }

  def is_pdf?
    self.content_type == "application/pdf"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
    has_one_attached :image
end

app/models/editor.rb
class Editor < ApplicationRecord
    belongs_to :assignment
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments
    has_one_attached :image
end

app/models/student.rb
class Student < ApplicationRecord
  validates :first_name,  presence: true
  validates :last_name,   presence: true
  validates :email,   presence: true
  validates :password, presence: true

  has_many :assignments
  has_secure_password

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :assignments, dependent: :destroy
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    
  # def index
  #   @student = Student.all
    
  # end

  # def show
    
  #   @student = Student.find(params[:id])
  # end

  # def new
  #   @student = Student.new
  # end

  # def create
  #  @student = Student.new(student_params)
  #  if @student.valid?
  #    @student.save
  #    redirect_to home_index_path
  #   end
  # end

  # def edit
  #   @student = Student.find(params[:id])
  # end

  # def update
  #   @student = Student.find(params[:id])
  #   @student.update(student_params)
  #   redirect_to home_index_path
  # end

  # def destroy
  # Student.destroy(params[:id])
  # redirect_to home_index_path
  # end

  # def student_params
  #   params.require(:student).permit(:first_name, :last_name)
  # end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
    @assignments = current_user.assignments.all
    @posts = current_user.posts.with_attached_image
  end

  def home
    if !logged_in?
      redirect_to login_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/calculator_helper.rb
module CalculatorHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/editors_helper.rb
module EditorsHelper
end

app/helpers/forum_helper.rb
module ForumHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/workspace_helper.rb
module WorkspaceHelper
end

app/views/admin/edit.html.erb
<% content_for :title, "Edit Profile" %>

<%= form_for(@student) do |form| %>
<label>First Name</label><br>
<%= form.text_field :first_name %> <br>

<label>Last Name</label><br>
<%= form.text_field :last_name %> <br>

<label>email</label><br>
<%= form.text_field :email %> <br>

<%= form.submit "Save", {class: "btn btn-success"}%>

<% end %>
<br>
<%= link_to "Back", :back %>

app/views/admin/new.html.erb
<% content_for :title, "Create Account" %>

<%= form_for(@student) do |form| %>
    <label> First name</label><br>
    <%= form.text_field :first_name %> <br>

    <label> Last name</label><br>
    <%= form.text_field :last_name %> <br>

    <label> E-mail</label><br>
    <%= form.email :email %> <br>

    <label> Password</label><br>
    <%= form.password :password %><br>

    <%= form.submit "Add Student", {class: "btn btn-success"} %><br><br>

    <%= link_to "Back", :back %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="google" content="notranslate"/>
    <title><%= yield(:title) %> - EmeraldApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="favicon" href="./images/favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Rum+Raisin" rel="stylesheet">
    <link rel="stylesheet" href="bootstrap.min.css">
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>


<body>

  <% if user_signed_in? %>
    <%# /#sidebar-toggle  %>

    <div id="wrapper" class="toggled" style="background-color: ">
      <div class="banner-bg" style="background-color: black">
        <div class="barnav fixed-top">
          <div class="emerald">
            <a class="btn btn-default sidenav-toggle menu-toggle mx-auto shine">
              <%= image_tag ("emerald.png"), :title => 'Click here to show/hide side bar' %>
              emerald
            </a>  
          </div>

          <div class="ml-auto" style="color: white;">
            
            <%= link_to destroy_user_session_path, method: :delete, :class => 'navbar-link' do %>
            <button type="button" class="btn btn-danger">Logout</button>
            <% end %>
          </div>
        </div>

        <%# Sidebar  %>
        <div id="sidebar-wrapper">
          <ul class="sidebar-nav">
            <li><p style="color: white" align="center">
            Logged in as <strong><%= current_user.email %></strong></p>
            </li>
            <li>
              <%= link_to root_path do %> Dashboard <% end %>
            </li>
            <li>
              <%= link_to forum_path do %>Public Forum<% end %>
            </li>
            <li>
              <%= link_to calculator_index_path, target:"_blank" do %>Calculator<% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>Edit Profile<% end %>
            </li>
          </ul>
        </div>
      </div>
  <% else %>

      <div class="barnav fixed-top shine" style="color: #066D0A;">
        <div class="emerald">
          <a class="shine"> 
          <%= link_to root_path, :class => 'navbar-link' do %>
          <%= image_tag ("emerald.png") %> 
          emerald
          </a>
          <% end %>
        </div>

        <div class="ml-auto ">
          <%= link_to new_user_registration_path, :class => 'navbar-link' do %>
            <button type="button" class="btn btn-warning">Sign Up</button>
          <% end %>
          <%= link_to new_user_session_path, :class => 'navbar-link' do %>
            <button type="button" class="btn btn-warning">Log In</button>
          <% end %>
        </div>
      </div>

  <% end %>
  
  

    <%= yield %>
  
  
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous" defer></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous" defer></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous" defer></script>
  <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

</body>
</html>